# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_elbo_grad <- function(par_vals, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block, n_ranef_par, n_fixef_par) {
    .Call(`_stanAD_get_elbo_grad`, par_vals, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block, n_ranef_par, n_fixef_par)
}

get_elbo_hvp <- function(par_vals, v, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block, n_ranef_par, n_fixef_par) {
    .Call(`_stanAD_get_elbo_hvp`, par_vals, v, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block, n_ranef_par, n_fixef_par)
}

get_neg_elbo_pois_glmm <- function(par, par_scaling, X, vec_Z, y_nz_idx, Zty, Xty, blocks_per_ranef, log_chol_par_per_block, terms_per_block, n, n_m_par, n_log_chol_par, n_b_par, total_blocks) {
    .Call(`_stanAD_get_neg_elbo_pois_glmm`, par, par_scaling, X, vec_Z, y_nz_idx, Zty, Xty, blocks_per_ranef, log_chol_par_per_block, terms_per_block, n, n_m_par, n_log_chol_par, n_b_par, total_blocks)
}

get_grad_pois_glmm <- function(par, par_scaling, X, vec_Z, y_nz_idx, Zty, Xty, blocks_per_ranef, log_chol_par_per_block, terms_per_block, n, n_m_par, n_log_chol_par, n_b_par, total_blocks) {
    .Call(`_stanAD_get_grad_pois_glmm`, par, par_scaling, X, vec_Z, y_nz_idx, Zty, Xty, blocks_per_ranef, log_chol_par_per_block, terms_per_block, n, n_m_par, n_log_chol_par, n_b_par, total_blocks)
}

get_elbo_pois_glmm_MFVB <- function(par_vals, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block, n_ranef_par, n_fixef_par) {
    .Call(`_stanAD_get_elbo_pois_glmm_MFVB`, par_vals, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block, n_ranef_par, n_fixef_par)
}

#' @export
fit_pois_glmm_block_posterior_ccd <- function(m, S_log_chol, b, link_offset, n_nz_terms_per_col, terms_per_block, blocks_per_ranef, log_chol_par_per_block, Zty, Xty, X, Z_i, Z_j, Z_x, Z, Z2, elbo_tol, num_iter, is_mfvb) {
    .Call(`_stanAD_fit_pois_glmm_block_posterior_ccd`, m, S_log_chol, b, link_offset, n_nz_terms_per_col, terms_per_block, blocks_per_ranef, log_chol_par_per_block, Zty, Xty, X, Z_i, Z_j, Z_x, Z, Z2, elbo_tol, num_iter, is_mfvb)
}

H <- function(x, a) {
    .Call(`_stanAD_H`, x, a)
}

log_cholesky_grad <- function(l_params, A) {
    .Call(`_stanAD_log_cholesky_grad`, l_params, A)
}

get_n_nz_terms <- function(n_nz_terms_per_col, blocks_per_ranef, terms_per_block) {
    .Call(`_stanAD_get_n_nz_terms`, n_nz_terms_per_col, blocks_per_ranef, terms_per_block)
}

create_ranef_Z <- function(n_nz_terms, blocks_per_ranef, terms_per_block, values) {
    .Call(`_stanAD_create_ranef_Z`, n_nz_terms, blocks_per_ranef, terms_per_block, values)
}

create_y_nz_idx <- function(n_nz_terms, blocks_per_ranef, terms_per_block, Z_i) {
    .Call(`_stanAD_create_y_nz_idx`, n_nz_terms, blocks_per_ranef, terms_per_block, Z_i)
}

structure_output <- function(par, blocks_per_ranef, log_chol_par_per_block, terms_per_block, n_m_par, n_log_chol_par, n_b_par, total_blocks) {
    .Call(`_stanAD_structure_output`, par, blocks_per_ranef, log_chol_par_per_block, terms_per_block, n_m_par, n_log_chol_par, n_b_par, total_blocks)
}

