# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_elbo_grad <- function(m, log_s, b, sigma_log_chol, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block) {
    .Call(`_stanAD_get_elbo_grad`, m, log_s, b, sigma_log_chol, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block)
}

get_elbo_hvp <- function(m, log_s, b, v, sigma_log_chol, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block) {
    .Call(`_stanAD_get_elbo_hvp`, m, log_s, b, v, sigma_log_chol, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block)
}

get_elbo_pois_glmm_MFVB <- function(m, log_s, b, sigma_log_chol, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block) {
    .Call(`_stanAD_get_elbo_pois_glmm_MFVB`, m, log_s, b, sigma_log_chol, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block)
}

H <- function(x, a) {
    .Call(`_stanAD_H`, x, a)
}

log_cholesky_grad <- function(l_params, A) {
    .Call(`_stanAD_log_cholesky_grad`, l_params, A)
}

