# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_elbo_grad <- function(par_vals, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block, n_ranef_par, n_fixef_par) {
    .Call(`_stanAD_get_elbo_grad`, par_vals, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block, n_ranef_par, n_fixef_par)
}

get_elbo_hvp <- function(par_vals, v, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block, n_ranef_par, n_fixef_par) {
    .Call(`_stanAD_get_elbo_hvp`, par_vals, v, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block, n_ranef_par, n_fixef_par)
}

get_elbo_pois_glmm_MFVB <- function(par_vals, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block, n_ranef_par, n_fixef_par) {
    .Call(`_stanAD_get_elbo_pois_glmm_MFVB`, par_vals, Zty, Xty, X, Z, Z2, blocks_per_ranef, terms_per_block, n_ranef_par, n_fixef_par)
}

#' @export
fit_pois_glmm_block_posterior_ccd <- function(m, S_log_chol, b, link_offset, n_nz_terms_per_col, terms_per_block, blocks_per_ranef, log_chol_par_per_block, Zty, Xty, X, Z_i, Z_j, Z_x, Z, Z2, elbo_tol, num_iter, is_mfvb) {
    .Call(`_stanAD_fit_pois_glmm_block_posterior_ccd`, m, S_log_chol, b, link_offset, n_nz_terms_per_col, terms_per_block, blocks_per_ranef, log_chol_par_per_block, Zty, Xty, X, Z_i, Z_j, Z_x, Z, Z2, elbo_tol, num_iter, is_mfvb)
}

H <- function(x, a) {
    .Call(`_stanAD_H`, x, a)
}

log_cholesky_grad <- function(l_params, A) {
    .Call(`_stanAD_log_cholesky_grad`, l_params, A)
}

